### PR TITLE
Custom commands to support accounts

### PR DESCRIPTION
**Pull request by tuxcanfly**
refs: https://github.com/davecgh/btcwallet/pull/7

### CODE REVIEW

**Comment by davecgh** [comment]
Since btcws is going away completely once conformal/btjson#34 drops, we'll need to move these there.

**Comment by davecgh** [comment]
I don't see any additional tests for the new commands.  Did they not get committed?

**Comment by tuxcanfly** [comment]
@davecgh sorry, must have overlooked it. Added them now.

**Comment by davecgh** [comment]
OK

**Pull request merged**
